name: Build Spring Boot Native Images (Matrix)

on:
  push:
    branches: [master]
  workflow_dispatch:

jobs:
  native-image:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        arch: [amd64, arm64]

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Set up QEMU (for cross-arch emulation)
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build native image with GraalVM via Maven
        run: |
          docker run --rm --platform=linux/${{ matrix.arch }} \
            -v "$PWD":/workspace -w /workspace \
            -e MAVEN_OPTS="-Dmaven.repo.local=/workspace/.m2" \
            ghcr.io/graalvm/native-image:ol8-java17-22.3.3 \
           ./mvnw -Pnative package

      - name: Upload native binary
        uses: actions/upload-artifact@v4
        with:
          name: spring-boot-native-${{ matrix.arch }}
          path: target/spring-boot-native
