name: GraalVM Native Image Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  JAVA_VERSION: '21'
  IMAGE_NAME: 'spring-boot-native'

jobs:
  build-native:
    strategy:
      matrix:
        os: [ubuntu-latest]
        arch: [amd64, arm64]
    runs-on: ${{ matrix.os }}
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up GraalVM
        uses: graalvm/setup-graalvm@v1
        with:
          java-version: ${{ env.JAVA_VERSION }}
          native-image-musl: 'true'
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Build with Maven
        run: |
          # For ARM64, we need to use Dockerized build
          if [ "${{ matrix.arch }}" = "arm64" ]; then
            docker run --rm \
              -v "$PWD":/project \
              -w /project \
              ghcr.io/graalvm/native-image-community:24.0.1-muslib-ol8-20250415 \
              mvn -Pnative package
          else
            mvn -Pnative package
          fi
          ls -l target

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: native-image-${{ matrix.arch }}
          path: target/${{ env.IMAGE_NAME }}
