# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Java CI with Maven

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: [ubuntu-latest, ubuntu-latest-arm64]

    steps:
    - uses: actions/checkout@v4

    - name: Setup GraalVM
      uses: graalvm/setup-graalvm@v1
      with:
        java-version: '21'
        distribution: 'graalvm'
        native-image-musl: 'true'
        github-token: ${{ secrets.GITHUB_TOKEN }}
        cache: 'maven'

    - name: Build native with Maven
      run: |
        mvn -B -Pnative \
            -Dnative.image.cache=true \
            -Dnative-image.parallelism=4 \
            -DskipTests \
            package
        ls -l target
