name: Build Native Images (Matrix)

on:
  push:
    branches: [master]
  workflow_dispatch:

jobs:
  native-image:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        arch: [amd64, arm64]

    steps:
      - uses: actions/checkout@v4

      - name: Set up QEMU (for arm64 emulation)
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Build JAR with Maven
        run: ./mvnw -Pnative native:compile

      - name: Build native image for ${{ matrix.arch }}
        run: |
          docker run --rm --platform linux/${{ matrix.arch }} \
            -v "$PWD":/workspace -w /workspace \
            ghcr.io/graalvm/native-image:ol8-java17-22.3.3 \
            native-image --no-fallback -H:Name=myapp-${{ matrix.arch }} -cp target/*.jar

      - name: Upload ${{ matrix.arch }} binary
        uses: actions/upload-artifact@v4
        with:
          name: myapp-${{ matrix.arch }}
          path: myapp-${{ matrix.arch }}
