name: Build Spring Boot Native Images (Matrix)

on:
  push:
    branches: [master]
  workflow_dispatch:

jobs:
  native-image:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Setup GraalVM
        uses: graalvm/setup-graalvm@v1
        with:
          java-version: '24'
          distribution: 'graalvm'
          native-image-musl: 'true'
          github-token: ${{ secrets.GITHUB_TOKEN }}
          cache: 'maven'

      - name: Build native with Maven
        run: |
          mvn -B -DskipTests -Pnative clean package

      - name: Upload native binary
        uses: actions/upload-artifact@v4
        with:
          name: spring-boot-native
          path: target/spring-boot-native
